#!/usr/bin/env bash
# validate-skill-frontmatter.sh
# PreToolUse hook on Write|Edit when target path contains /skills/ under CLAUDE_PROJECT_DIR/k0d3.
# Hard rules (per docs/conventions.md):
#   - Real YAML parser (yq or python3 yaml); never sed/grep YAML values for downstream use
#   - Never pass YAML values as subprocess args; stdin or env only
#   - On any internal error: exit 0 + log + stderr echo (fail-open)
#   - Bypass: K0D3_SKIP_VALIDATOR=1 → exit 0 immediately (logged to bypass log)
#   - Manual disable: chmod -x this file
#
# Opt-in in hooks/hooks.json; enable after test-validator.sh passes.

set -uo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-}"
LOG_DIR="$PROJECT_DIR/.claude/logs"
LOG="$LOG_DIR/validator-errors.log"
BYPASS_LOG="$LOG_DIR/validator-bypass.log"

# Bypass via env var — logged so silent indefinite bypass is detectable.
# If CLAUDE_PROJECT_DIR is unset we can't write the log file, but we still
# surface the bypass on stderr so it's not entirely silent.
if [[ "${K0D3_SKIP_VALIDATOR:-}" == "1" ]]; then
  if [[ -n "$PROJECT_DIR" ]]; then
    mkdir -p "$LOG_DIR" 2> /dev/null || true
    echo "[$(date +%Y-%m-%dT%H:%M:%S%z)] K0D3_SKIP_VALIDATOR=1 — bypassed" >> "$BYPASS_LOG" 2> /dev/null || true
  else
    echo "[validate-skill-frontmatter] K0D3_SKIP_VALIDATOR=1 — bypassed (no audit log: CLAUDE_PROJECT_DIR unset)" >&2
  fi
  exit 0
fi

# Scope: only fire when CLAUDE_PROJECT_DIR ends with k0d3
if [[ -z "$PROJECT_DIR" || ! "$PROJECT_DIR" =~ /k0d3/?$ ]]; then
  exit 0
fi

mkdir -p "$LOG_DIR" 2> /dev/null || true

# Read tool input from stdin (CC convention)
INPUT="$(cat 2> /dev/null || true)"

# Extract file_path field from the JSON input
FILE_PATH="$(echo "$INPUT" | python3 -c 'import sys, json; d=json.load(sys.stdin); print(d.get("tool_input",{}).get("file_path",""))' 2> /dev/null || echo "")"

# Only act on writes to skills/**
if [[ -z "$FILE_PATH" || ! "$FILE_PATH" =~ /skills/ ]]; then
  exit 0
fi

# Real YAML parser via python (never sed/grep YAML values).
# Now also enforces body line cap (>200 lines) at write-time, matching the
# lint rule in _validate_skills.py (C6).
# Pass the validator script as -c so stdin stays available for the JSON envelope.
# `python3 - <<EOF` would consume stdin for the script source and leave nothing
# for json.load(sys.stdin) to read.
VALIDATOR_SCRIPT="$(
  cat << 'PY'
import json, sys, pathlib
try:
    import yaml
except ImportError:
    sys.exit(0)  # Fail-open: no PyYAML, allow the write

target = sys.argv[1]
data = json.load(sys.stdin)
content = data.get("tool_input", {}).get("content") or data.get("tool_input", {}).get("new_string", "")
is_skill_md = pathlib.Path(target).name == "SKILL.md"

if not content.startswith("---"):
    if is_skill_md:
        print("SKILL.md must start with YAML frontmatter (--- block). Run scripts/new-skill.sh <slug> to scaffold a valid skill, or see docs/conventions.md for the required fields.")
        sys.exit(1)
    sys.exit(0)
parts = content.split("---", 2)
if len(parts) < 3:
    print("frontmatter missing closing ---")
    sys.exit(1)

try:
    fm = yaml.safe_load(parts[1]) or {}
except Exception as e:
    print(f"YAML parse error: {e}")
    sys.exit(1)
if not isinstance(fm, dict):
    print("frontmatter is not a mapping")
    sys.exit(1)

errors = []
if not fm.get("name"):
    errors.append("missing name")
if not fm.get("description"):
    errors.append("missing description")
md = fm.get("metadata") or {}
if not md.get("type"):
    errors.append("missing metadata.type")
if not md.get("status"):
    errors.append("missing metadata.status")
if md.get("status") == "stub":
    errors.append("status:stub forbidden")
if md.get("invokes_shell") is False and md.get("status") == "active" and not md.get("shell_reviewed"):
    errors.append("invokes_shell=false + status=active requires shell_reviewed")

slug = pathlib.Path(target).parent.name
if fm.get("name") and fm["name"] != slug:
    errors.append(f"name '{fm['name']}' != directory '{slug}'")

# Body cap: >200 lines fails, mirroring lint. skill-discovery is exempt
# because it is auto-generated by scripts/generate-skill-graph.sh and holds
# the full topic→slug routing table. See docs/conventions.md § Skill
# frontmatter (the "Body cap ~200 lines" rule) for the rationale.
body = parts[2]
if slug != "skill-discovery" and body.count("\n") > 200:
    errors.append(f"body {body.count(chr(10))} lines > 200 cap")

if errors:
    for e in errors:
        print(e)
    sys.exit(1)
PY
)"
ERRORS="$(printf '%s' "$INPUT" | python3 -c "$VALIDATOR_SCRIPT" "$FILE_PATH" 2>&1)"

# Always exit 0 (fail-open). Log issues and echo to stderr (CC surfaces stderr).
if [[ -n "$ERRORS" ]]; then
  # Fence user paths in the log to prevent markdown injection (C12.3 + log hygiene)
  SAFE_PATH="$(printf '%s' "$FILE_PATH" | tr '\n' ' ' | sed 's/`/'"'"'/g')"
  echo "[validate-skill-frontmatter] $SAFE_PATH: $ERRORS" >&2
  echo "[validate-skill-frontmatter] To bypass: K0D3_SKIP_VALIDATOR=1 (one-shot) or chmod -x hooks/validate-skill-frontmatter.sh (persistent). See docs/conventions.md §Validator bypass." >&2
  echo "[$(date +%Y-%m-%dT%H:%M:%S%z)] $SAFE_PATH: $ERRORS" >> "$LOG" 2> /dev/null || true
fi

exit 0
