#!/usr/bin/env python3
"""generate-skill-graph.sh helper. Writes docs/skill-graph.md (Mermaid) AND
skills/skill-discovery/SKILL.md (routing table). Optional --prune-drafts."""

from __future__ import annotations

import datetime as dt
import os
import pathlib
import re
import sys

try:
    import yaml  # noqa: F401  — surfaces import error early; _skill_utils uses it
except ImportError:
    print("FAIL: PyYAML not installed (`pip install pyyaml`)", file=sys.stderr)
    sys.exit(1)

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _skill_utils import parse_frontmatter

REPO = pathlib.Path(__file__).resolve().parent.parent
os.chdir(REPO)

prune_drafts = "--prune-drafts" in sys.argv


SKILLS_DIR = REPO / "skills"
DOCS = REPO / "docs"
DOCS.mkdir(exist_ok=True)
GRAPH = DOCS / "skill-graph.md"

skill_dirs = sorted(p for p in SKILLS_DIR.iterdir() if p.is_dir()) if SKILLS_DIR.exists() else []
skills: list[tuple[str, dict, pathlib.Path]] = []
for d in skill_dirs:
    if d.name.startswith("_probe-"):
        continue
    sk = d / "SKILL.md"
    if not sk.exists():
        continue
    fm = parse_frontmatter(sk)
    status = (fm.get("metadata") or {}).get("status")
    if prune_drafts and status == "draft":
        continue
    skills.append((d.name, fm, sk))

# Mermaid graph
with GRAPH.open("w") as f:
    f.write("# Skill graph (auto-generated by scripts/generate-skill-graph.sh)\n\n")
    f.write("> Do not edit by hand. Regenerated on every commit by the pre-commit hook.\n\n")
    f.write("```mermaid\ngraph LR\n")
    for slug, fm, _ in skills:
        related = (fm.get("metadata") or {}).get("related") or []
        if related:
            for r in related:
                f.write(f"  {slug} --> {r}\n")
        else:
            f.write(f"  {slug}\n")
    f.write("```\n")

# Routing table for skill-discovery
disc_dir = SKILLS_DIR / "skill-discovery"
disc_dir.mkdir(parents=True, exist_ok=True)
disc = disc_dir / "SKILL.md"

ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
today = dt.date.today().isoformat()
kw: dict[str, set[str]] = {}
# Generic English words that are poor routing keys — they get mined from skill
# descriptions ("keep all", "the user wants", "drop filler", "less tokens") and only
# add noise to the table. Domain words (terse, concise, brief, filler, …) are kept.
STOPWORDS = {
    "the",
    "and",
    "for",
    "use",
    "with",
    "via",
    "from",
    "all",
    "less",
    "keep",
    "drop",
    "want",
    "wants",
    "user",
}
for slug, fm, _ in skills:
    if slug in {"skill-discovery", "using-k0d3"}:
        continue
    # Drafts must not appear in the routing table — they signal "not ready",
    # and Skill(skill-discovery) is what determines what users get loaded.
    # The Mermaid graph above DOES include drafts so forward links stay visible.
    if (fm.get("metadata") or {}).get("status") == "draft":
        continue
    # Words from slug itself
    for w in set(slug.split("-")):
        if len(w) < 3:
            continue  # filter 1-2 char fragments to reduce noise
        kw.setdefault(w, set()).add(slug)
    # Also pull keywords from description so a skill named `rest-essentials` shows
    # up under "api"; a skill named `go-mcp` shows up under "mcp", etc.
    desc = (fm.get("description") or "").lower()
    for w in set(re.findall(r"[a-z][a-z0-9-]{2,}", desc)):
        if w in STOPWORDS or len(w) < 3:
            continue
        kw.setdefault(w, set()).add(slug)
        # Add singular form for trailing-`s` plurals so "apis" → "api" too.
        # Honour STOPWORDS here as well, else a plural ("keeps", "users") would
        # smuggle a stopword singular ("keep", "user") past the filter above.
        if len(w) > 3 and w.endswith("s") and not w.endswith("ss"):
            sing = w[:-1]
            if sing not in STOPWORDS:
                kw.setdefault(sing, set()).add(slug)
    # Explicit keywords from frontmatter (manual routing entries — primary use case
    # is restoring routing that pack deletions removed without re-bundling).
    md = fm.get("metadata") or {}
    extra_kws = md.get("keywords") if isinstance(md, dict) else None
    if isinstance(extra_kws, list):
        for raw in extra_kws:
            w = str(raw).lower().strip()
            if len(w) >= 3 and w not in STOPWORDS:  # match the description-mining floor
                kw.setdefault(w, set()).add(slug)

# Preserve the human shell-review attestation across regenerations. shell_reviewed
# records that a person read this file's shell usage for safety; re-stamping it with
# today's date on every routine regen would falsely advance the attestation (this file
# is invokes_shell:false and its body is generated, so a regen reviews no shell calls).
# Keep the existing value; only stamp a fresh date on first generation.
shell_reviewed = f"valksor {today}"
if disc.exists():
    prev = (parse_frontmatter(disc).get("metadata") or {}).get("shell_reviewed")
    if prev:
        shell_reviewed = str(prev)

with disc.open("w") as f:
    f.write("---\n")
    f.write("name: skill-discovery\n")
    f.write(
        "description: Routing table — given a topic keyword, returns recommended skill slugs to load. Auto-generated; do not edit body.\n"
    )
    f.write(f'last-generated: "{ts}"\n')
    f.write("metadata:\n")
    f.write("  type: meta\n")
    f.write("  status: active\n")
    f.write("  invokes_shell: false\n")
    f.write(f'  shell_reviewed: "{shell_reviewed}"\n')
    f.write("  related: [using-k0d3]\n")
    f.write("---\n\n")
    f.write("# Skill discovery\n\n")
    f.write(
        "When the user mentions a topic, look up here. Each row maps a keyword to one or more relevant skill slugs. To add manual routing entries, add a `keywords:` field to the target skill's frontmatter and regenerate via `bash scripts/generate-skill-graph.sh` — manual edits to this file will be overwritten.\n\n"
    )
    f.write("| Keyword | Skills |\n|---|---|\n")
    for k in sorted(kw):
        # kw[k] is a set — sort for stable output
        f.write(f"| {k} | {', '.join(sorted(kw[k]))} |\n")

print(f"Wrote {GRAPH} and {disc}", file=sys.stderr)
