#!/usr/bin/env bash
# install-codex-hooks.sh — MIGRATION / UNINSTALLER ONLY (Codex CLI).
#
# k0d3 used to install its hooks out-of-band into ~/.codex/hooks.json because older
# Codex could not bundle plugin hooks. Current Codex (0.142.x) supports plugin-channel
# hooks, so k0d3 now ships them via the plugin (hooks/hooks.codex.json, referenced by
# .codex-plugin/plugin.json and generated by scripts/generate-codex-hooks.sh).
#
# This script's only remaining job is to REMOVE a prior out-of-band install so it does
# not double-fire alongside the plugin hooks (the stale verify-before-stop.sh copy also
# re-emits the old {decision,reason} Stop schema that Codex rejects). It strips ONLY
# k0d3's entries (commands referencing ~/.codex/k0d3 or ./.codex/k0d3); your own hooks
# are left untouched.
#
# Usage:
#   scripts/install-codex-hooks.sh --uninstall            # global  (~/.codex)
#   scripts/install-codex-hooks.sh --project --uninstall  # project (./.codex)
#   scripts/install-codex-hooks.sh --uninstall --dry-run  # preview, write nothing
#
# Installing hooks is no longer this script's job: a bare (or --print/install-style)
# invocation prints this notice and exits non-zero so old muscle-memory and CI callers
# notice the change. Hooks come from the plugin — run `codex` and use /hooks to trust
# them (do NOT use --bypass-hook-trust).
#
# Requires: bash 3.2+, jq.
set -eu

SCOPE="global"
DRY=0
UNINSTALL=0

for arg in "$@"; do
  case "$arg" in
    --project) SCOPE="project" ;;
    --dry-run) DRY=1 ;;
    --uninstall) UNINSTALL=1 ;;
    -h | --help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    --print | --install) ;; # legacy install-era flags — handled by the notice below
    *)
      echo "unknown arg: $arg" >&2
      exit 2
      ;;
  esac
done

deprecation_notice() {
  cat >&2 << 'EOF'
install-codex-hooks.sh no longer installs hooks.

k0d3 hooks now ship via the plugin channel (hooks/hooks.codex.json). Install/upgrade the
plugin, then run `codex` and use /hooks to review and trust them (not --bypass-hook-trust).

This script only UNINSTALLS a prior out-of-band install:
  scripts/install-codex-hooks.sh --uninstall            # ~/.codex/hooks.json
  scripts/install-codex-hooks.sh --project --uninstall  # ./.codex/hooks.json
EOF
}

if [ "$UNINSTALL" != "1" ]; then
  deprecation_notice
  exit 1
fi

command -v jq > /dev/null 2>&1 || {
  echo "error: jq is required" >&2
  exit 1
}

if [ "$SCOPE" = "project" ]; then
  BASE="$PWD/.codex"
else
  BASE="$HOME/.codex"
fi
HOOKS_HOME="$BASE/k0d3"   # stable runtime copy left by old installs
TARGET="$BASE/hooks.json" # the file Codex reads
HD="$HOOKS_HOME/hooks"

# Strip k0d3 entries: any hook command referencing the old runtime copy ($HD), then
# drop events whose list went empty. Leaves the user's own hooks intact.
strip_from_target() {
  jq --arg hd "$HD" '
    if .hooks then
      .hooks |= with_entries(
        .value |= map(select([ .hooks[]?.command // "" | contains($hd) ] | any | not)))
      | .hooks |= with_entries(select(.value | length > 0))
    else . end
  ' "$TARGET"
}

if [ -f "$TARGET" ]; then
  # Only act if k0d3 entries are actually present, so the message is truthful.
  HAD=$(jq --arg hd "$HD" '[.. | objects | select(has("command")) | .command | select(contains($hd))] | length' "$TARGET" 2> /dev/null || echo 0)
  if [ "${HAD:-0}" = "0" ]; then
    echo "no k0d3 hooks in $TARGET — nothing to remove"
  else
    OUT="$(strip_from_target)"
    if [ "$DRY" = "1" ]; then
      echo "[dry-run] would rewrite $TARGET to:"
      echo "$OUT"
    else
      # Atomic: write to a temp file and rename, so an interrupted run never
      # truncates the user's hooks.json into an empty/partial file.
      TMP="$(mktemp)"
      trap 'rm -f "$TMP"' EXIT
      printf '%s\n' "$OUT" > "$TMP" && mv "$TMP" "$TARGET"
      echo "removed k0d3 hooks from $TARGET"
    fi
  fi
else
  echo "no $TARGET — nothing to remove"
fi

if [ -d "$HOOKS_HOME" ]; then
  if [ "$DRY" = "1" ]; then
    echo "[dry-run] would rm -rf $HOOKS_HOME"
  else
    rm -rf "$HOOKS_HOME"
    echo "removed $HOOKS_HOME"
  fi
fi
