#!/usr/bin/env bash
# install-git-hooks.sh [--force]
# Inputs: optional --force to overwrite an existing .git/hooks/pre-commit
# Exit codes: 0 on success; 1 if .git missing or pre-commit exists without --force
# Side effects: writes .git/hooks/pre-commit (wrapper that runs validate-skills + regenerates skill-graph)
#
# Uses `set -e` in the generated pre-commit so a failing generate-skill-graph.sh
# does NOT silently swallow errors — the commit fails rather than proceeding with a stale graph.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
  esac
done

if [[ ! -d .git ]]; then
  echo "FAIL: .git not found. Run \`git init\` first." >&2
  exit 1
fi

HOOK_PATH=".git/hooks/pre-commit"
if [[ -e "$HOOK_PATH" && $FORCE -eq 0 ]]; then
  echo "FAIL: $HOOK_PATH exists. Re-run with --force to overwrite." >&2
  exit 1
fi

cat > "$HOOK_PATH" << 'HOOK'
#!/usr/bin/env bash
# pre-commit (auto-generated by scripts/install-git-hooks.sh)
set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# 1) Lint
bash scripts/validate-skills.sh

# 2) Regenerate skill graph + skill-discovery, stage the diff
bash scripts/generate-skill-graph.sh
git add docs/skill-graph.md skills/skill-discovery/SKILL.md 2>/dev/null || true
HOOK

chmod +x "$HOOK_PATH"
echo "Installed $HOOK_PATH" >&2
